version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /app/init_db.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      SMTP_USER: "kurn0sovm@yandex.ru"
      SMTP_PASSWORD: "xTOYS?eY/K2U9nJ?"
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/mydatabase"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

  email-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python email_consumer.py
    depends_on:
      - kafka
      - web
    environment:
      SMTP_SERVER: "smtp.yandex.ru"
      SMTP_PORT: 587
      SMTP_USER: "kurn0sovm@yandex.ru"
      SMTP_PASSWORD: "xTOYS?eY/K2U9nJ?"
      EMAIL_FROM: "kurn0sovm@yandex.ru"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
